'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {motion} from 'motion/react';
import {Activity,ArrowDownRight,ArrowRight,ArrowUpRight,Beaker,BookOpen,Box,Check,ChevronRight,Clock3,Code2,Copy,Database,DollarSign,ExternalLink,FlaskConical,Gauge,GitBranch,Layers3,LoaderCircle,Orbit,Play,Plus,Radio,RefreshCw,ShieldCheck,Sparkles,Terminal,Workflow,Zap} from 'lucide-react';
import {ResponsiveContainer,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip,BarChart,Bar,Legend} from 'recharts';
import {ExecutionGraph} from './execution-graph';
import {recipeFrontier} from '@/lib/frontier';
import {useRun} from '@/hooks/use-run';
import {api,money,shortModel} from '@/lib/api';
import type {Candidate,Experiment,Mode,Observation,Policy,Run,Shadow,Status} from '@/types';

const navigation=[{name:'Mission Control',icon:Workflow},{name:'Runs',icon:Layers3},{name:'Shadow Lab',icon:FlaskConical},{name:'Calibration',icon:Gauge},{name:'Policies',icon:GitBranch},{name:'Benchmarks',icon:Activity}];
const samples=[{name:'Python algorithm',icon:Code2,prompt:'Implement a Python function longest_consecutive(nums) that finds the length of the longest consecutive sequence in O(n). Explain complexity.'},{name:'Exact reasoning',icon:Sparkles,prompt:'Calculate 17 * 23. Return only the number.'},{name:'JSON + repair',icon:Box,prompt:'Extract Ada, age 36 into JSON with exactly name (string) and age (integer). Return JSON only. Repair demo.'}];
const jsonSpec={type:'json',schema:{type:'object',properties:{name:{type:'string'},age:{type:'integer'}},required:['name','age'],additionalProperties:false},expected:{name:'Ada',age:36}};

function Empty({icon:Icon=Database,title,children}:{icon?:typeof Database;title:string;children:React.ReactNode}){return <div className="empty-state"><div className="empty-icon"><Icon size={25}/></div><h3>{title}</h3><p>{children}</p></div>;}
function Tag({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`tag ${tone}`}>{children}</span>;}
function PanelTitle({eyebrow,title,action}:{eyebrow?:string;title:string;action?:React.ReactNode}){return <div className="panel-title"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{action}</div>;}

export function Dashboard(){
 const [page,setPage]=useState('Mission Control');const [mode,setMode]=useState<Mode>('live');const [status,setStatus]=useState<Status|null>(null);const [online,setOnline]=useState(false);
 const [prompt,setPrompt]=useState(samples[0].prompt);const [quality,setQuality]=useState(.9);const [budget,setBudget]=useState(.02);const [latency,setLatency]=useState(45);const [priority,setPriority]=useState('standard');const [sample,setSample]=useState(0);
 const [runs,setRuns]=useState<Run[]>([]);const [shadows,setShadows]=useState<Shadow[]>([]);const [policies,setPolicies]=useState<Policy[]>([]);const [experiments,setExperiments]=useState<Experiment[]>([]);const [observations,setObservations]=useState<Observation[]>([]);const [recipeRows,setRecipeRows]=useState<Candidate[]>([]);
 const [notice,setNotice]=useState<string|null>(null);const [actionBusy,setActionBusy]=useState(false);const [copied,setCopied]=useState(false);
 const [reuseCache,setReuseCache]=useState(true);
 const labUrl=process.env.NEXT_PUBLIC_LAB_URL||(process.env.NEXT_PUBLIC_DEPLOYED==='true'?null:'http://127.0.0.1:2718');
 const currentMode=useRef(mode);
 const clearEvidence=()=>{setRuns([]);setShadows([]);setPolicies([]);setExperiments([]);setObservations([]);setRecipeRows([]);};
 const live=useRun();
 const refresh=useCallback(async()=>{
  try{const [s,r,sh,p,e,o,rr]=await Promise.all([api<Status>('/status/integrations'),api<Run[]>(`/runs?mode=${mode}`),api<Shadow[]>(`/shadow?mode=${mode}`),api<Policy[]>(`/policies?mode=${mode}`),api<Experiment[]>(`/experiments?mode=${mode}`),api<Observation[]>(`/observations?mode=${mode}`),api<Candidate[]>(`/recipes?mode=${mode}`)]);if(currentMode.current!==mode)return;setStatus(s);if(s.default_mode==="simulation"&&mode!=="simulation"){currentMode.current="simulation";setMode("simulation");clearEvidence();return;}setRuns(r);setShadows(sh);setPolicies(p);setExperiments(e);setObservations(o);setRecipeRows(rr);setOnline(true);}catch{if(currentMode.current===mode)setOnline(false);}
 },[mode]);
 useEffect(()=>{let active=true;void refresh();const interval=setInterval(()=>{if(active)void refresh();},4000);return()=>{active=false;clearInterval(interval);};},[refresh]);
 useEffect(()=>{if(!live.busy)void refresh();},[live.busy,refresh]);
 const candidates=live.run?.candidate_recipes.length?live.run.candidate_recipes:[...live.events].reverse().find(e=>e.candidates)?.candidates??[];
 const selected=live.run?.selected_recipe??[...live.events].reverse().find(e=>e.selected_recipe)?.selected_recipe;
 const profile=live.run?.profile??[...live.events].reverse().find(e=>e.profile)?.profile;
 const schedulerReason=live.run?.scheduler_reason||[...live.events].reverse().find(e=>e.stage==='scheduler'&&e.status==='complete')?.message;
 const activeStage=[...live.events].reverse().find(e=>e.status==='active')?.stage;
 const final=live.run?.status==='completed';const lastEvaluation=live.run?.final_evaluation;
 const frontier=useMemo(()=>recipeFrontier(observations),[observations]);
 const activeJob=experiments.find(e=>e.status==='running');
 const act=async(work:()=>Promise<unknown>,message:string)=>{setActionBusy(true);setNotice(null);try{await work();setNotice(message);await refresh();}catch(e){setNotice(e instanceof Error?e.message:'Action failed');}finally{setActionBusy(false);}};
 const run=()=>{setNotice(null);void live.submit({prompt,quality_target:quality,max_budget_usd:budget,max_latency_seconds:latency,priority,mode,bypass_cache:!reuseCache,...(sample===2?{evaluation_spec:jsonSpec}:{})});};
 const chooseMode=(value:Mode)=>{if(live.busy||status?.default_mode==='simulation'&&value==='live')return;currentMode.current=value;clearEvidence();setMode(value);live.clear();setNotice(null);};
 const copy=async()=>{if(!live.run?.output)return;try{await navigator.clipboard.writeText(live.run.output);setCopied(true);setTimeout(()=>setCopied(false),1500);}catch{setNotice('Clipboard unavailable. Select the result text to copy it.');}};

 return <div className="app-shell">
  <aside className="sidebar"><a href="#" className="brand" onClick={()=>setPage('Mission Control')} aria-label="Optara home"><div className="brand-mark"><Orbit size={25}/></div><span>optara<span className="brand-dot">.</span></span></a><div className="workspace"><span className="workspace-avatar">O</span><div>Optara workspace<small>Personal / local</small></div><ChevronRight size={14}/></div><div className="nav-label">CONTROL PLANE</div><nav aria-label="Main navigation">{navigation.map(({name,icon:Icon})=><button key={name} className={`nav-item ${page===name?'selected':''}`} onClick={()=>setPage(name)} aria-current={page===name?'page':undefined}><Icon size={18}/><span>{name}</span>{name==='Mission Control'&&<span className="nav-live"/>}{name==='Runs'&&runs.length>0&&<span className="nav-count">{runs.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-lab"><Beaker size={19}/><strong>Your intelligence lab</strong><p>Turn execution evidence into better decisions.</p>{labUrl?<a href={labUrl} target="_blank" rel="noreferrer">Open marimo Lab <ArrowUpRight size={14}/></a>:<a href="https://github.com/rohit16111999/optara#marimo--molab-experiment-lab" target="_blank" rel="noreferrer">Run the marimo lab <ArrowUpRight size={14}/></a>}</div><div className="nav-label">INTEGRATIONS</div>{(['inference','weave','mcp','aria'] as const).map(key=><div className="integration-mini" key={key} title={status?.[key]?.detail}><span className={`status-dot ${status?.[key]?.available?'green':'amber'}`}/><span>{{inference:'W&B Inference',weave:'Weave',mcp:'W&B MCP',aria:'ARIA'}[key]}</span><small>{status?.[key]?.available?'Connected':'Unavailable'}</small></div>)}<button className="verify-link" onClick={()=>void act(()=>api('/status/verify',{}),'Connection checks finished. A real run verifies inference and trace delivery.')} disabled={actionBusy}><RefreshCw size={13} className={actionBusy?'spin':''}/>Verify connections</button><div className="sidebar-footer"><span className="avatar">RM</span><div>Local development<small>models-student1155</small></div></div></div></aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={13}/><strong>{page}</strong></div><div className="topbar-right"><span className="system-status"><span className={`status-dot ${online?'green':'amber'}`}/>{online?'Control plane online':'Connecting to backend'}</span><span className="top-divider"/><a href={status?.weave_url??'https://wandb.ai/models-student1155/optara/weave'} target="_blank" rel="noreferrer">Weave project <ArrowUpRight size={13}/></a><span className="version">v0.1</span></div></header>
   <main className="main-content"><div className="page-heading"><div><div className="heading-kicker"><span className="tiny-line"/> INTELLIGENCE, OPTIMIZED.</div><h1>{page}</h1><p>{page==='Mission Control'?'Spend intelligence where it matters. Let the evidence choose the execution.':page==='Shadow Lab'?'Explore better recipes. Protect the production result.':page==='Calibration'?'Measure capability before making promises.':page==='Policies'?'Every policy change starts with evidence.':page==='Benchmarks'?'Same tasks. Same constraints. Measured tradeoffs.':'Every decision, every check, every execution.'}</p></div><div className="mode-switch" aria-label="Execution mode"><button disabled={live.busy||status?.default_mode==='simulation'} className={mode==='live'?'active':''} onClick={()=>chooseMode('live')}><Radio size={13}/>Live W&B</button><button disabled={live.busy} className={mode==='simulation'?'active simulation-active':''} onClick={()=>chooseMode('simulation')}><Beaker size={13}/>Simulation</button></div></div>
   {mode==='simulation'&&<div className="simulation-banner"><Beaker size={15}/><strong>SIMULATION</strong><span>Local fixtures · no model calls or sponsor traces · evidence stored separately</span></div>}
   {!online&&<div className="notice error" role="status">Backend unavailable. Start Optara with .\start.ps1; the interface will reconnect automatically.</div>}
   {(notice||live.error)&&<div className="notice" role="status">{notice||live.error}<button onClick={()=>setNotice(null)} aria-label="Dismiss notice">×</button></div>}
   {page==='Mission Control'&&<>
    <section className="task-composer panel"><div className="composer-heading"><span><Terminal size={15}/> DEFINE YOUR TASK</span><Tag tone={mode==='simulation'?'purple':'neutral'}>{mode==='simulation'?'Local simulation':'W&B execution'}</Tag></div><label className="sr-only" htmlFor="task-prompt">Task prompt</label><textarea id="task-prompt" value={prompt} onChange={e=>{setPrompt(e.target.value);setSample(-1);}} placeholder="What should Optara solve?" maxLength={16000}/><div className="sample-row"><span>Try a task</span>{samples.map((s,i)=><button key={s.name} onClick={()=>{setPrompt(s.prompt);setSample(i);}} className={sample===i?'chosen':''}><s.icon size={12}/>{s.name}</button>)}<label className="cache-toggle"><input type="checkbox" checked={reuseCache} onChange={e=>setReuseCache(e.target.checked)}/>Reuse validated results</label></div><div className="constraints"><label className="quality-control"><span>Quality target <strong>{quality.toFixed(2)}</strong></span><input aria-label="Quality target" type="range" min="0.5" max="1" step="0.01" value={quality} onChange={e=>setQuality(Number(e.target.value))}/></label><label><span><DollarSign size={13}/> Max budget</span><div className="number-input"><span>$</span><input aria-label="Max budget" type="number" min="0.00001" max={status?.limits.max_request_cost??.05} step="0.005" value={budget} onChange={e=>setBudget(Number(e.target.value))}/><small>USD</small></div></label><label><span><Clock3 size={13}/> Deadline</span><div className="number-input"><input aria-label="Deadline" type="number" min="1" max="180" value={latency} onChange={e=>setLatency(Number(e.target.value))}/><small>seconds</small></div></label><label><span><Zap size={13}/> Priority</span><select aria-label="Priority" value={priority} onChange={e=>setPriority(e.target.value)}><option value="standard">Standard</option><option value="high">High</option><option value="background">Background</option></select></label><button className="run-button" disabled={live.busy||!prompt.trim()||budget<=0||latency<=0||budget>(status?.limits.max_request_cost??.05)} onClick={run}>{live.busy?<LoaderCircle size={17} className="spin"/>:<Play size={16} fill="currentColor"/>}{live.busy?'Optimizing…':'Run Optara'}<span>↗</span></button></div></section>
    <section className="graph-panel panel"><PanelTitle title="Execution topology" action={<div className="graph-meta"><span className={`status-dot ${live.busy?'purple':final?'green':'muted'}`}/>{live.busy?`${activeStage??'initializing'} · ${live.elapsed.toFixed(1)}s`:final?'Execution complete':'Ready for a task'}<span className="graph-meta-divider"/><span>LIVE FLOW</span></div>}/><ExecutionGraph events={live.events}/><div className="graph-footer"><div className="graph-legend"><span><i/>Pending</span><span><i className="purple"/>Active</span><span><i className="green"/>Complete</span><span><i className="amber"/>Needs attention</span></div><span className="graph-thesis">One request. The right amount of intelligence.</span></div></section>
    <div className="kpi-grid"><Kpi icon={ShieldCheck} label="QUALITY" value={live.run?.quality!=null?live.run.quality.toFixed(2):'—'} detail={lastEvaluation?`${lastEvaluation.deterministic?'Objective checks':'Estimated quality'} · target ${(live.run?.task.quality_target??quality).toFixed(2)}`:'Actual output, evaluated'} tone="cyan"/><Kpi icon={DollarSign} label="EXECUTION COST" value={live.run?money(live.run.total_cost):'—'} detail={mode==='simulation'?'Simulation · no paid inference':`Budget ${money(live.run?.task.max_budget_usd??budget)} · token-based cost`} tone="purple"/><Kpi icon={Clock3} label="LATENCY" value={live.busy?`${live.elapsed.toFixed(1)}s`:live.run?`${live.run.total_latency.toFixed(2)}s`:'—'} detail={`End-to-end · ${live.run?.task.max_latency_seconds??latency}s deadline`} tone="blue"/><Kpi icon={Gauge} label="SLA RESULT" value={final?(live.run?.sla_hit?'HIT':'MISS'):live.run?.status==='failed'?'BLOCKED':'—'} detail={final?(live.run?.sla_hit?'All three constraints satisfied':live.run?.sla_failures.join(' · ')??''):'Quality + budget + deadline'} tone={live.run?.sla_hit?'green':'amber'}/></div>
    <div className="decision-layout"><section className="panel candidates-panel"><PanelTitle title="Candidate recipes" eyebrow="THE DECISION" action={<Tag>{candidates.length?`${candidates.length} candidates`:'Top-K = 3'}</Tag>}/>{candidates.length?<div className="recipe-grid">{candidates.map((c,i)=><RecipeCard key={c.recipe.recipe_id} candidate={c} index={i}/>)}</div>:<div className="candidate-empty"><Layers3 size={25}/><div><strong>The recipe is the unit of intelligence.</strong><p>Model, token budget, reasoning, verification and repair — compared together after you run a task.</p></div><div className="recipe-ghosts"><span>01</span><span>02</span><span>03</span></div></div>}{schedulerReason&&<div className="scheduler-reason"><BrainIcon/><div><strong>Why this recipe</strong><p>{schedulerReason}</p></div></div>}</section><section className="panel profile-panel"><PanelTitle title="Task intelligence" action={<ScanIcon/>}/><div className="profile-data"><div><span>Family</span><strong>{profile?.task_family??'Awaiting task'}</strong></div><div><span>Difficulty</span><strong>{profile?profile.difficulty.toFixed(2):'—'}</strong></div><div><span>Evaluation</span><strong>{profile?.evaluation_type??'—'}</strong></div><div><span>Cache</span><strong>{live.run?.cache_hit?'HIT':profile?(profile.cacheable?'Eligible':'Freshness bypass'):'—'}</strong></div><div><span>Policy</span><strong>{live.run?.policy_version?`v${live.run.policy_version}`:'Evidence gathering'}</strong></div></div><div className="profile-footnote"><ShieldCheck size={14}/>{selected?`${selected.max_output_tokens} output tokens · ${selected.repair_limit} repair max`:'Bounded spend. Bounded execution.'}</div></section></div>
    <div className="bottom-layout"><section className="panel result-panel"><PanelTitle title="Execution result" action={<div className="result-actions">{live.run?.trace_url&&<a href={live.run.trace_url} target="_blank" rel="noreferrer"><ExternalLink size={13}/>Trace recorded</a>}<button onClick={copy} disabled={!live.run?.output}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Copied':'Copy'}</button></div>}/>{live.run?.error?<div className="result-error"><ShieldCheck size={23}/><h3>Execution stopped safely</h3><p>{live.run.error}</p><small>No automatic retry was attempted.</small></div>:live.run?.output?<><pre data-testid="result-output">{live.run.output}</pre><div className="evaluation-note"><ShieldCheck size={15}/><div><strong>{lastEvaluation?.evaluation_type.replaceAll('_',' ')}</strong><p>{lastEvaluation?.explanation}</p></div></div><ExecutionEvidence run={live.run}/><div className="result-footer"><span>{live.run.executions.reduce((a,e)=>a+e.total_tokens,0)} tokens · {live.run.repair_steps.length} repairs</span><button onClick={()=>void act(()=>api(`/runs/${live.run!.run_id}/shadow`,{}),'Shadow experiment started. Follow the comparison in Shadow Lab.')} disabled={actionBusy||live.run.cache_hit}><FlaskConical size={13}/>Test a shadow recipe</button></div></>:<Empty icon={Sparkles} title="Intelligence has a destination.">Your evaluated answer appears here, with the evidence behind it.</Empty>}</section><section className="panel log-panel"><PanelTitle title="Live activity" action={<Tag>{live.events.length} events</Tag>}/><div className="event-log" role="log" aria-label="Execution activity">{live.events.length?live.events.slice(-40).map(e=><div className={`event-line ${e.status}`} key={e.sequence}><time>{new Date(e.timestamp).toLocaleTimeString('en-GB')}</time><span className="event-point"/><div><strong>{e.stage}</strong><p>{e.message}</p></div></div>):<div className="terminal-empty"><span className="terminal-prompt">optara ~</span> control plane ready<br/><span className="muted-text">Waiting for your first task.</span><span className="terminal-cursor"/></div>}</div></section></div>
    <section className="sponsor-strip"><div><Orbit size={21}/><strong>Built for the complete loop</strong><span>Execution → evidence → improvement</span></div><div className="sponsor-names"><span title={status?.inference.detail}><i className={status?.inference.available?'green':'amber'}/>W&B Inference</span><span title={status?.weave.detail}><i className={status?.weave.available?'green':'amber'}/>Weave</span><span title={status?.marimo.detail}><i className={status?.marimo.available?'green':'amber'}/>marimo</span><span title={status?.aria.detail}><i className="amber"/>ARIA · unavailable</span></div></section>
   </>}
   {page==='Runs'&&<section className="panel"><PanelTitle title="Execution history" action={<Tag>{runs.length} runs · {mode}</Tag>}/>{runs.length?<div className="table-scroll"><table><thead><tr><th>Task / recipe</th><th>Quality</th><th>Cost</th><th>Latency</th><th>Status</th><th/></tr></thead><tbody>{runs.map(r=><tr key={r.run_id}><td><strong>{r.task.prompt.slice(0,85)}</strong><small>{r.selected_recipe?.name??'No recipe selected'} · {r.run_id.slice(0,8)} {r.cache_hit?'· cache hit':''}</small></td><td>{r.quality?.toFixed(2)??'—'}</td><td>{money(r.total_cost)}</td><td>{r.total_latency.toFixed(2)}s</td><td><Tag tone={r.sla_hit?'green':r.status==='failed'?'amber':'neutral'}>{r.status==='completed'?(r.sla_hit?'SLA HIT':'SLA MISS'):r.status}</Tag></td><td><button className="icon-button" aria-label={`Inspect run ${r.run_id.slice(0,8)}`} onClick={()=>{void live.load(r.run_id).catch(e=>setNotice(e.message));setPage('Mission Control');}}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>:<Empty title="Your execution history starts here.">Run a task from Mission Control to record its complete decision path.</Empty>}</section>}
   {page==='Shadow Lab'&&<><div className="feature-banner"><div className="feature-orbit"><FlaskConical size={35}/></div><div><span className="eyebrow">SAFE EXPLORATION</span><h2>A better recipe deserves a fair test.</h2><p>Production serves the answer. A separate, budget-limited execution tests an alternative. One result never proves a policy.</p></div><Tag tone="purple">{Math.round((status?.limits.shadow_rate??.08)*100)}% exploration</Tag></div><div className="kpi-grid three"><Kpi icon={FlaskConical} label="SHADOW EXPERIMENTS" value={String(shadows.length)} detail="Paired with a production execution" tone="purple"/><Kpi icon={ShieldCheck} label="PRODUCTION ISOLATION" value="Protected" detail="Shadow never replaces the served answer" tone="cyan"/><Kpi icon={GitBranch} label="PROMOTION GATE" value={`${status?.limits.policy_min_evidence??5}+ pairs`} detail="Quality protected · improvement required" tone="blue"/></div><section className="panel"><PanelTitle title="Production vs. shadow" action={<Tag tone="purple">Independent outcomes</Tag>}/>{shadows.length?<div className="shadow-list">{shadows.map(s=><div className="shadow-comparison" key={s.id}><div className="shadow-head"><span>{s.family} <small> / {s.production_run.slice(0,8)}</small></span><Tag tone={s.status==='completed'?'purple':'amber'}>{s.status}</Tag></div><div className="shadow-pair"><div><span className="eyebrow">PRODUCTION</span><h3>{s.production_recipe}</h3><div className="mini-metrics"><span><strong>{s.production_quality?.toFixed(2)??'—'}</strong>quality</span><span><strong>{money(s.production_cost)}</strong>cost</span><span><strong>{s.production_latency?.toFixed(2)??'—'}s</strong>latency</span></div></div><span className="versus">vs</span><div className="shadow-side"><span className="eyebrow">SHADOW CANDIDATE</span><h3>{s.shadow_recipe}</h3><div className="mini-metrics"><span><strong>{s.shadow_quality?.toFixed(2)??'—'}</strong>quality</span><span><strong>{money(s.shadow_cost)}</strong>cost</span><span><strong>{s.shadow_latency?.toFixed(2)??'—'}s</strong>latency</span></div></div></div><div className="shadow-verdict"><GitBranch size={14}/>{s.error??s.promotion?.reason??'Waiting for the alternative execution'}</div></div>)}</div>:<Empty icon={FlaskConical} title="Give the next recipe a chance.">Complete an uncached task, then choose “Test a shadow recipe” in the result panel. Production output stays unchanged.</Empty>}</section></>}
   {page==='Policies'&&<><div className="policy-pipeline">{['Candidate','Shadow testing','Evidence gate','Production'].map((s,i)=><div key={s}><span>0{i+1}</span><strong>{s}</strong>{i<3&&<ArrowRight size={17}/>}</div>)}</div><section className="panel"><PanelTitle title="Policy evolution" action={<Tag>{observations.length} observations</Tag>}/>{policies.length?<div className="policy-list">{policies.map(p=><div className="policy-card" key={p.policy_id}><div className="policy-icon"><GitBranch size={21}/></div><div className="policy-main"><div className="policy-card-heading"><h3>{p.task_family} policy <span>v{p.version}</span></h3><Tag tone={p.status==='production'?'green':'purple'}>{p.status}</Tag></div><p>{p.creation_reason}</p><code>{p.recipe_preferences.join(', ')}</code><div className="evidence-progress"><div style={{width:`${Math.min(100,p.evidence_count/5*100)}%`}}/></div><small>{p.evidence_count} paired observations · {p.comparison.reason} · confidence {p.confidence.toFixed(2)}</small></div><button className="secondary-button" disabled={!p.comparison.eligible||actionBusy||p.status==='production'} onClick={()=>void act(()=>api(`/policies/${p.policy_id}/promote`,{}),'Evidence-gated policy promoted.')}>Promote <ArrowUpRight size={14}/></button></div>)}</div>:<Empty icon={GitBranch} title="Better decisions are earned.">Policies appear after shadow experiments. Promotion requires at least five distinct paired executions, protected quality, and demonstrated cost, latency or SLA improvement.</Empty>}</section><div className="method-note"><BookOpen size={18}/><div><strong>Small samples deserve honest uncertainty.</strong><p>Recipe quality uses a Beta(1,1) prior. Paired policy comparisons use confidence bounds and distinct production runs. Simulation evidence never changes live policy.</p></div></div></>}
   {(page==='Calibration'||page==='Benchmarks')&&<><section className="panel experiment-toolbar"><div><span className="eyebrow">{page==='Calibration'?'CONTROLLED OFFLINE EXPERIMENT':'FIXED BASELINES · ADAPTIVE CONTROL'}</span><h2>{page==='Calibration'?'Know your execution frontier.':'Prove the tradeoff.'}</h2><p>{page==='Calibration'?'A small suite measures recipe quality, token cost, and end-to-end latency.':'Always Cheap, Always Strong and Optara use identical tasks, constraints and evaluators.'}</p></div><div><Tag>2 models · 3 tasks · $0.03 cap</Tag><button className="primary-button" disabled={actionBusy||!!activeJob} onClick={()=>void act(()=>api(page==='Calibration'?'/calibration':'/benchmark',{mode,max_models:2,max_cost:.03,task_count:3}),`${page} started. Results update as each task completes.`)}>{activeJob?<LoaderCircle className="spin" size={16}/>:<Play size={15}/>} {activeJob?'Experiment running…':page==='Calibration'?'Run calibration':'Run benchmark'}</button></div></section>
    {page==='Calibration'?<div className="calibration-layout"><section className="panel"><PanelTitle title="Quality / cost frontier" action={<Tag>{observations.length} measured outcomes</Tag>}/>{observations.length?<div className="chart-container"><ResponsiveContainer width="100%" height="100%"><ScatterChart><CartesianGrid stroke="#222a3c" strokeDasharray="3 3"/><XAxis type="number" dataKey="cost" name="Cost" stroke="#78839b" tickFormatter={v=>`$${v}`} label={{value:'Cost (USD)',position:'insideBottom',offset:-10,fill:'#78839b'}}/><YAxis type="number" dataKey="quality" name="Quality" domain={[0,1]} stroke="#78839b"/><Tooltip contentStyle={{background:'#131a29',border:'1px solid #313b52',borderRadius:10}} cursor={{strokeDasharray:'3 3'}}/><Legend/><Scatter data={frontier.filter(o=>!o.frontier)} fill="#59677e" name="Dominated within family"/><Scatter data={frontier.filter(o=>o.frontier)} fill="#40c8c5" name="Pareto frontier within family"/></ScatterChart></ResponsiveContainer></div>:<Empty icon={Gauge} title="No calibration data yet.">Run a small calibration to plot observed quality against cost. No performance is assumed from model names.</Empty>}</section><section className="panel"><PanelTitle title="Recipe registry" action={<Tag>{recipeRows.length} recipes</Tag>}/><div className="registry-list">{recipeRows.length?recipeRows.map(r=><div key={r.recipe.recipe_id}><span className="registry-icon"><Layers3 size={16}/></span><div><strong>{r.recipe.name}</strong><small>{shortModel(r.recipe.model_id)}</small></div><span>{r.metrics.observations}<small>samples</small></span></div>):<Empty title="Discover your models.">Verify W&B connections to populate the registry from the authenticated models API.</Empty>}</div></section></div>:<BenchmarkChart experiments={experiments.filter(e=>e.kind==='benchmark')}/>}
    <section className="panel experiment-history"><PanelTitle title="Experiment history"/>{experiments.filter(e=>e.kind===(page==='Calibration'?'calibration':'benchmark')).length?<div className="experiment-list">{experiments.filter(e=>e.kind===(page==='Calibration'?'calibration':'benchmark')).map(e=><div key={e.id}><div><strong>{e.kind} <span className="muted-text">/ {e.id.slice(0,8)}</span></strong><small>{e.error??e.notes?.[0]??new Date(e.created_at).toLocaleString()}</small></div><span>{e.groups?Object.keys(e.groups).length:0} strategies</span><Tag tone={e.status==='completed'?'green':e.status==='failed'?'amber':'purple'}>{e.status}</Tag></div>)}</div>:<p className="quiet-placeholder">No experiments in {mode} mode yet. Calibration never runs automatically.</p>}</section></>}
   <footer className="main-footer"><span>OPTARA <span>Intelligence, Optimized.</span></span><span>Kubernetes schedules compute. Optara schedules AI intelligence.</span></footer>
   </main></div></div>;
}

function BrainIcon(){return <Sparkles size={17}/>;}function ScanIcon(){return <Orbit size={17} className="muted-text"/>;}
function Kpi({icon:Icon,label,value,detail,tone}:{icon:typeof Gauge;label:string;value:string;detail:string;tone:string}){return <div className={`kpi-card ${tone}`}><div className="kpi-label"><span>{label}</span><Icon size={16}/></div><div className="kpi-value">{value}</div><p>{detail}</p><div className="kpi-accent"/></div>;}
function RecipeCard({candidate:c,index}:{candidate:Candidate;index:number}){return <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:index*.06,duration:.25}} className={`recipe-card ${c.selected?'chosen-recipe':''}`} title={c.rejection_reason??'Selected by the scheduler'}><div className="recipe-card-top"><span className="recipe-index">0{index+1}</span>{c.selected?<Tag tone="purple"><Check size={11}/> Selected</Tag>:<Tag>Alternative</Tag>}</div><h3>{c.recipe.name}</h3><p className="recipe-model">{shortModel(c.recipe.model_id)}</p><div className="recipe-config"><span>{c.recipe.reasoning??'Standard'} reasoning</span><span>{c.recipe.max_output_tokens} tokens</span><span>{c.recipe.verifier_enabled?'Verifier on':'Verifier off'}</span></div><div className="recipe-metrics"><div><span>Quality</span><strong>{c.metrics.observations?c.metrics.expected_quality.toFixed(2):'Uncalibrated'}</strong></div><div><span>Cost</span><strong>{money(c.metrics.expected_cost)}</strong></div><div><span>Latency</span><strong>{c.metrics.observations?`${c.metrics.expected_latency.toFixed(2)}s`:'Prior: 15s'}</strong></div></div><div className="recipe-evidence"><Database size={11}/>{c.metrics.observations} observations{!c.metrics.observations&&' · insufficient data'}</div></motion.div>;}
function BenchmarkChart({experiments}:{experiments:Experiment[]}){const latest=experiments.find(e=>e.groups&&Object.keys(e.groups).length);const rows=useMemo(()=>latest?Object.entries(latest.groups).map(([name,g])=>({name,...g})):[],[latest]);return <section className="panel"><PanelTitle title="Strategy comparison" action={<Tag>{latest?'Measured execution outcomes':'Insufficient data'}</Tag>}/>{rows.length?<><div className="chart-container benchmark-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} barCategoryGap="28%"><CartesianGrid stroke="#222a3c" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" stroke="#8590a8"/><YAxis domain={[0,1]} stroke="#8590a8"/><Tooltip contentStyle={{background:'#131a29',border:'1px solid #313b52',borderRadius:10}}/><Legend/><Bar dataKey="mean_quality" name="Mean quality" fill="#9e86ff" radius={[5,5,0,0]}/><Bar dataKey="sla_hit_rate" name="SLA hit rate" fill="#40c8c5" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><div className="table-scroll"><table><thead><tr><th>Strategy</th><th>Quality</th><th>Mean cost</th><th>Latency</th><th>SLA hit rate</th><th>Cost / success</th></tr></thead><tbody>{rows.map(r=><tr key={r.name}><td><strong>{r.name}</strong></td><td>{r.mean_quality?.toFixed(2)??'—'}</td><td>{money(r.mean_cost)}</td><td>{r.mean_latency?.toFixed(2)??'—'}s</td><td>{r.sla_hit_rate==null?'—':`${(r.sla_hit_rate*100).toFixed(0)}%`}</td><td>{money(r.cost_per_success)}</td></tr>)}</tbody></table></div><p className="chart-note">{latest?.notes?.[0]??'Small sample: do not infer general savings from these results.'}</p></>:<Empty icon={Activity} title="Evidence before claims.">Calibrate first to identify the highest-quality observed recipe, then run a small comparison. Savings appear only when measured.</Empty>}</section>;}

function ExecutionEvidence({run}:{run:Run}){return <details className="execution-evidence" open><summary>Execution evidence</summary><dl><div><dt>Model ID</dt><dd>{run.selected_recipe?.model_id}</dd></div><div><dt>Recipe</dt><dd>{run.selected_recipe?.recipe_id}</dd></div><div><dt>Input / output / total tokens</dt><dd>{run.executions.reduce((n,e)=>n+e.input_tokens,0)} / {run.executions.reduce((n,e)=>n+e.output_tokens,0)} / {run.executions.reduce((n,e)=>n+e.total_tokens,0)}</dd></div><div><dt>Quality / target</dt><dd>{run.quality?.toFixed(2)} / {run.task.quality_target.toFixed(2)}</dd></div><div><dt>Cost / budget</dt><dd>{money(run.total_cost)} / {money(run.task.max_budget_usd)}</dd></div><div><dt>Latency / deadline</dt><dd>{run.total_latency.toFixed(3)}s / {run.task.max_latency_seconds}s</dd></div><div><dt>Cache</dt><dd>{run.cache_hit?'HIT · validated reuse':'MISS · model execution'}</dd></div><div><dt>Shadow</dt><dd>{run.shadow_result?.status??'Not sampled / not requested'}</dd></div><div><dt>Policy</dt><dd>{run.policy_version?`Production v${run.policy_version}`:'Evidence gathering · no production preference'}</dd></div></dl>{run.repair_steps.map(step=><p key={step.attempt}>Repair {step.attempt}: {step.reason} → score {step.score_after??'unavailable'}</p>)}</details>;}
